### PR TITLE
Scale PM_RA by cos(dec) when applying proper motion

### PR DESCRIPTION
**Pull request by jeanconn**
Scale PM_RA by cos(dec) when applying proper motion.

### CODE REVIEW

**Comment by jeanconn** [comment]
There aren't really any tests here in this package, but I installed this to a test ska and ran on APR0918A and confirmed  that in obsid 20162 the MON window now has a "guess" agasc_id of "*1058813608" (so that position match code worked) and the hover-over for star 1058813608 shows a yag/zag of 67.56, 32.92 which matches the Python agasc position using "2018:104" as the data for the proper motion correction.

**Review by taldcroft — APPROVED** [review]

**Comment by taldcroft** [comment]
To make the test a bit more reproducible and obvious, can you just copy/paste the Python code and corresponding Perl code (with results) for the position of star ID 1058813608 on Jan. 1, 2020?

**Comment by jeanconn** [comment]
Sounds good.  I'll just put that here in the PR (won't try to make a Perl test for it).

**Comment by taldcroft** [comment]
Yes, sorry, I meant exactly that about pasting into the PR comments.

**Comment by jeanconn** [comment]
And I didn't want the extra work of figuring out Perl tests again, but then by the time I'd written a little separate Perl script to call the Ska::AGASC code to recalculate a position for 1058813608, I basically had a test, so I just pushed it.  If we need more of a proper spherical distance check, I'll need to dig that out.

**Review by taldcroft — APPROVED** [review]

**Pull request merged**
